### ISSUE TITLE
typeof not declared in C++ on GCC

### ISSUE THREAD

**Issue by mokafolio** [sheredom/utest.h#19] opened 2019-08-09 22:23 UTC
If I try to use utest using any of the macros that internally use `typeof` for a c++ program using gcc 8.3.0, I get 

> utest.h:423:5: error: ‘typeof’ was not declared in this scope

A fix would be to use `__typeof__` instead. I can fork and create a pull request if that is a valid fix and I am not missing anything.

I think the same is true for clang, not sure right now though.

**Comment by sheredom** [comment] 2019-09-09 09:59
I'll look into this - thanks!

**Comment by sheredom** [comment] 2019-09-14 12:52
I cannot seem to reproduce this with either GCC 8 or 9 https://travis-ci.org/sheredom/utest.h/jobs/584919082

Any tips? Otherwise I'm going to have to close this as cannot reproduce!

**Comment by mokafolio** [comment] 2019-09-14 17:49
I am on GCC 8.3 and compile utest in a c++ project. If i don't use any c++ classes/structs it compiles fine, but this for instance won't:

`#include <vector>
#include "utest.h"

UTEST(foo, bar) {
	std::vector<int> foo = {1, 2, 3};
	ASSERT_EQ(foo.size(), 3);
}

UTEST_MAIN();`

this gives me something like this:

> In file included from ../main.cpp:2:
../main.cpp: In function ‘void utest_run_foo_bar(int*)’:
../utest.h:427:5: error: ‘typeof’ was not declared in this scope
     typeof(y) xEval = (x);                                                     \
     ^~~~~~
../utest.h:470:25: note: in expansion of macro ‘UTEST_ASSERT’
 #define ASSERT_EQ(x, y) UTEST_ASSERT(x, y, ==)
                         ^~~~~~~~~~~~
../main.cpp:6:2: note: in expansion of macro ‘ASSERT_EQ’
  ASSERT_EQ(foo.size(), 3);
  ^~~~~~~~~
...


Based on my research `typeof` is not part of c++ on any of the major compilers, only the more covert `__typeof__` is.

**Comment by sheredom** [comment] 2019-09-15 07:49
Very weird I cannot reproduce (even with your test!) - but I've changed it over to __typeof__ in https://github.com/sheredom/utest.h/pull/23. Can you verify locally please?

**Comment by mokafolio** [comment] 2019-09-27 01:58
Sorry for the delay, got sucked into work. I'll check it out this weekend!

**Closed** 2019-12-23 21:37 UTC

**Comment by mokafolio** [comment] 2019-12-24 09:34
Apologies, zoned out. I just tested it and it certainly fixes it. I recommend to switch to __typeof__ if you want the lib to consistently work with cpp compilers.

**Comment by yyuuttaaoo** [comment] 2021-01-28 02:25
Maybe you can specify -Dtypeof="__typeof__" in gcc flag as a work around.
